// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSF6LPOkItmfMItJqgTpq6bnCCE8FIZfI',
    appId: '1:169388457291:web:6e318c504b11e94b393cce',
    messagingSenderId: '169388457291',
    projectId: 'fresh-veggies-b859e',
    authDomain: 'fresh-veggies-b859e.firebaseapp.com',
    storageBucket: 'fresh-veggies-b859e.appspot.com',
    measurementId: 'G-CMLMW6DQJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2xUkfbMduKe3Qkhlpag9P5JQPbq67PI',
    appId: '1:169388457291:android:abd8fcfa73093b22393cce',
    messagingSenderId: '169388457291',
    projectId: 'fresh-veggies-b859e',
    storageBucket: 'fresh-veggies-b859e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vwOq-45vU5wZfHd8gz6rvcUJe2ERsmo',
    appId: '1:169388457291:ios:bb26ca69346bb1dc393cce',
    messagingSenderId: '169388457291',
    projectId: 'fresh-veggies-b859e',
    storageBucket: 'fresh-veggies-b859e.appspot.com',
    iosClientId: '169388457291-fgm3mkvln4qba2hnc3mgpnm68n4ue3sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshVeggies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vwOq-45vU5wZfHd8gz6rvcUJe2ERsmo',
    appId: '1:169388457291:ios:bb26ca69346bb1dc393cce',
    messagingSenderId: '169388457291',
    projectId: 'fresh-veggies-b859e',
    storageBucket: 'fresh-veggies-b859e.appspot.com',
    iosClientId: '169388457291-fgm3mkvln4qba2hnc3mgpnm68n4ue3sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshVeggies',
  );
}
